    version: '3.5'

    services:
      postgres:
        image: postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          PGDATA: /data/postgres
        volumes:
          - postgres:/data/postgres
        ports:
          - "5432:5432"
        networks:
          - postgres
        restart: unless-stopped

      pgadmin:
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@root.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "8081:80"
        depends_on:
          - postgres
        networks:
          - postgres

      redis:
        container_name: redis-cache
        image: redis:7.0-alpine
        ports:
          - 6379:6379
        volumes:
          - redis:/data

    networks:
      postgres:
        driver: bridge

    volumes:
        postgres:
        redis:
